### ISSUE TITLE
我的專案可以使用 anime-data 資料嗎?

### ISSUE THREAD

**Issue by malagege** [ACGNTaiwan/Anime-List#44]
請問我的專案可以使用[anime-data](https://github.com/ACGNTaiwan/Anime-List/tree/master/anime-data)裡面資料嗎?

我的專案應該還沒到side project，只是練習寫 Vue3 小程式，功能可以針對有看的新番動畫做標記和排名，然後做分享。[連結](https://malagege.github.io/vue-myanimelist/#/202110#W3sibmFtZSI6IuWuv-WRvei_tOmfvyDlkb3pgYvnr4Dmi40iLCJzaG93Ijp0cnVlLCJvcmRlciI6IjUifSx7Im5hbWUiOiLpgIbovYnkuJbnlYznmoTpm7vmsaDlsJHlpbMiLCJzaG93Ijp0cnVlLCJvcmRlciI6IjUifSx7Im5hbWUiOiLpl5zmlrzliY3ovKnlvojnhankurrnmoTkuosiLCJzaG93Ijp0cnVlLCJvcmRlciI6IjUifSx7Im5hbWUiOiLmnIjoiIfokIrljaHoiIflkLjooYDlhazkuLsiLCJzaG93Ijp0cnVlLCJvcmRlciI6IjMifSx7Im5hbWUiOiI4NuS4jeWtmOWcqOeahOaIsOWNgCAiLCJzaG93Ijp0cnVlLCJvcmRlciI6IjQifSx7Im5hbWUiOiLnhKHogbfovYnnlJ8gIiwic2hvdyI6dHJ1ZSwib3JkZXIiOiLlv4XnnIsifSx7Im5hbWUiOiLlm6DngrrkuI3mmK_nnJ_mraPnmoTlpKXkvLTogIzooqvpgJDlh7rli4fogIXpmorkvI3mtYHokL3liLDpgorlooPlsZXplovmhaLmtLvkurrnlJ8iLCJzaG93Ijp0cnVlLCJvcmRlciI6IjIifSx7Im5hbWUiOiLkuJbnlYzpoILlsJbmmpfmrrrogIXovYnnlJ_ngrrnlbDkuJbnlYzosrTml48iLCJzaG93Ijp0cnVlLCJvcmRlciI6IjEifSx7Im5hbWUiOiLpgLLljJbkuYvlr6bouI_kuIrli53liKnnmoTkurrnlJ8iLCJzaG93Ijp0cnVlLCJvcmRlciI6IjUifSx7Im5hbWUiOiLkuJbnlYznm6HpoK3nmoTogZbpqI7lo6siLCJzaG93Ijp0cnVlfSx7Im5hbWUiOiJNdXYtTHV2IEFsdGVybmF0aXZlIiwic2hvdyI6dHJ1ZSwib3JkZXIiOiI2In1d)
Github: https://github.com/malagege/vue-myanimelist

我會用到JSON資料和圖片連結。
因為圖片好像是你們手動整理上傳的，所以不敢直接用。
不知大大能不能讓我使用，感謝。

**Comment by gnehs** [comment]
可以的喔，根據 [WTFPL License](https://github.com/ACGNTaiwan/Anime-List/blob/master/LICENSE) 你想拿去幹嘛，就拿去幹嘛
