### ISSUE TITLE
世界盡頭的聖騎士 季度錯誤

### ISSUE THREAD

**Issue by Haraguroicha** [ACGNTaiwan/Anime-List#68]
https://github.com/ACGNTaiwan/Anime-List/blob/93ff426eab85b2fb8136928e5da8cb20183cba3d/anime-data/anime2023.10.json#L90-L100

這邊應該是第二季，第一季依照 wiki 是在 2021 年共 12 集

https://github.com/ACGNTaiwan/Anime-List/blob/93ff426eab85b2fb8136928e5da8cb20183cba3d/anime-data/anime2021.10.json#L101-L111

**Comment by james58899** [comment]
你為什麼不直接PR
